apiVersion: v1
kind: Service
metadata:
  name: mc-ragnarok-nodeport
spec:
  type: NodePort
  selector:
    app: mc-ragnarok
  ports:
    - protocol: TCP
      name: minecraft
      port: 25565
      targetPort: 25565
